### ISSUE TITLE
I follow the tutorial but in my webUI there are not all the boxes that appear in the video

### ISSUE THREAD

**Issue by tommdraws** [dr413677671/PromptGallery-stable-diffusion-webui#21]
what i'm supposed to be seeing
![video](https://user-images.githubusercontent.com/85202736/212832947-196ac7b7-d634-41b9-9db4-795c8df9126d.png)
what i see
![image](https://user-images.githubusercontent.com/85202736/212833003-908ed5cf-67cc-475c-bdc9-6bfef6bcba57.png)

**Comment by dr413677671** [comment]
Could you paste the outputs of browser console？

**Comment by dr413677671** [comment]
Or paste the log from webui.

**Comment by jbnv** [comment]
I'm having the same issue. The text instructions make little sense because they don't match what I'm seeing. For example, in the section "Start Prompt Gallery," there is this instruction: "Select avatar (model for demo) -> Select prompt-sets -> Click "send WebUI"" and an image containing a set of button bars that aren't present in my window. (This is in addition to the problem tommdraws is describing. I can't tell what the prompt script is actually supposed to be doing. How do I populate the avatars in the first place?)

I'm getting numerous exceptions in the WebUI terminal. I can post them here if you want.

Can you get someone with a better command of English to write the instructions?

**Comment by dr413677671** [comment]
Yes log is needed.
